### ISSUE TITLE
Newer kernel submodule required for RISC-V support

### ISSUE THREAD

**Issue by victor-dumitrescu** [hermit-os/hermit-rs#507]
I'm using this crate to compile kernels to RISC-V. The issue I have is that the version of `kernel` pinned in this repository doesn't support RISC-V. Would pinning a newer version pose a problem? Thanks!

**Comment by mkroening** [comment]
> Would pinning a newer version pose a problem?

Not at all! I opened https://github.com/hermit-os/hermit-rs/pull/508.

Let us know when you need this available as release as well. :)

**Comment by victor-dumitrescu** [comment]
Many thanks! If possible, a release would further simplify our workflow.

**Comment by mkroening** [comment]
`hermit = "0.7.2"` is available on crates.io: https://crates.io/crates/hermit/0.7.2 👍

**Comment by victor-dumitrescu** [comment]
Amazing, thanks!
